name: Testing NHL Workflow
on: workflow_dispatch
jobs:
 test: 
   runs-on: windows-latest
   steps:
    - name: run testing
      run: actions/checkout@v4
    - name: Install dependecies
      run: npm ci
    - name: Test application
      run: npm run wdio ./wdio github/workflows/nhl_testing.yml
