name: Deploy Shop page
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Run test
      uses: actions/checkout@v4
    - name: Install dependecies
      run: npm ci
    - name: Run application
      run: npm run wdio ./wdio test/specs/shop.page.js
  lint:
    runs-on: windows-latest
    needs: test
    steps:
    - name: Run test
      uses: actions/checkout@v4
    - name: Install dependecies
      run: npm ci
    - name: Lint application
      run: npm run wdio ./lint .
  build:
  runs-on: windows-latest
  needs: lint
  steps:
  - name: Run test
    uses: actions/checkout@v4
  - name: Install dependecies
    run: npm ci
  - name: Build application
    run: npm run wdio ./build .
  - name: Deploy
    run: echo "Deploying..."