name: Testimg Password Page
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: run test
      uses: actions/checkout@v4
    - name: Install dependecies
      run: npm ci
    - name: Testin Applications
      run: npm run wdio ./wdio test/specs/..js
  